version: "3.7"
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=vuttr
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
    ports:
      - 5435:5432
