version: "3.7"
services:
  app:
    image: vuttr
    container_name: vuttr
    ports:
      - 3000:3000
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=vuttr
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
    ports:
      - 5435:5432
